include:
  - board: seeduino_xiao_ble
    shield: totem_left rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeduino_xiao_ble
    shield: totem_right rgbled_adapter
  - board: seeduino_xiao_ble
    shield: settings_reset
# there is no settingsreset (needed) for the XIAO
